from django.db import models


class Module(models.Model):
    ModelName = models.CharField(max_length=500, null=False, unique=True)
    ModelDescription = models.CharField(max_length=2000, null=False)
    ManufactureID = models.IntegerField(null=True)
    ModuleManufactureDate = models.DateField(null=True, blank=True)
    ModuleLengthWidth = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    ModuleWeight = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    IndividualCellArea = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    CellTechnology = models.CharField(max_length=500, null=False)
    CellManufacturer = models.CharField(max_length=500, null=False)
    PartNumber = models.CharField(max_length=500, null=False)
    CellManufacturingLocation = models.CharField(max_length=500, null=False)
    TotalNumberOfCells = models.IntegerField()
    NumberOfCellsInParallel = models.IntegerField()
    NumberOfCellsInSeries = models.IntegerField()
    ByPassDiodes = models.IntegerField()
    ByPassDiodeRating = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    ByPassDiodeMaxTemp = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    SeriesFuseRating = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    InterconnectMaterial = models.CharField(max_length=500, null=False)
    SupplierModelNumber = models.CharField(max_length=500, null=False)
    SuperstrateType = models.CharField(max_length=500, null=False)
    SuperstratePartNumber = models.CharField(max_length=500, null=False)
    SuperstrateManufacturer = models.CharField(max_length=500, null=False)
    SubstrateType = models.CharField(max_length=500, null=False)
    SubstratePartNumber = models.CharField(max_length=500, null=False)
    SubstrateManufacturer = models.CharField(max_length=500, null=False)
    FrameType = models.CharField(max_length=500, null=False)
    FrameAdhesive = models.CharField(max_length=500, null=False)
    EncapsulantType = models.CharField(max_length=500, null=False)
    EncapsulantManufacturer = models.CharField(max_length=500, null=False)
    EncapsulantPartNumber = models.CharField(max_length=500, null=False)
    JunctionBoxType = models.CharField(max_length=500, null=False)
    JunctionBoxManufacturer = models.CharField(max_length=500, null=False)
    JunctionBoxPartNumber = models.CharField(max_length=500, null=False)
    JunctionBoxPottingMaterial = models.CharField(max_length=500, null=False)
    JunctionBoxAdhesive = models.CharField(max_length=500, null=False)
    CableType = models.CharField(max_length=500, null=False)
    ConnectorType = models.CharField(max_length=500, null=False)
    MaxSysVoltage = models.DecimalField(max_digits=5, decimal_places=2, null=False)
